### ISSUE TITLE
Verkeerd geplaatste dropdown menu

### ISSUE THREAD

**Issue by Tjoosten** [ScoutsGidsenVL/groepsadmin-client#15]
Hi, 

Op mijn macbook 13 inch. Zie ik een verkeerd geplaatste dropdown menu. 
<img width="564" alt="schermafbeelding 2016-03-29 om 01 56 21" src="https://cloud.githubusercontent.com/assets/5157609/14093881/92634640-f551-11e5-8da2-81bddcb48249.png">

Browser: Safari Versie 9.0.3 (11601.4.4)

**Comment by goback136** [comment]
Tim, dit zou idd opgelost zijn maar nog niet op laatste develop versie zijn gelanceerd

**Comment by Tjoosten** [comment]
alright!
