### ISSUE TITLE
Navigatie balk -> ingelogde gebruiker

### ISSUE THREAD

**Issue by Tjoosten** [ScoutsGidsenVL/groepsadmin-client#18]
Hi, 

woutersynhaeve staat momenteel nog hardcoded in de navigatie balk. Kunnen we dit niet uit de authencated user sessie halen en vervangen? Zodat de ingelogde gebruikersnaam hier word weergegeven. 

<img width="1155" alt="schermafbeelding 2016-04-14 om 16 44 03" src="https://cloud.githubusercontent.com/assets/5157609/14532133/4464d406-0260-11e6-9586-78b86a873f40.png">

**Comment by BramScheerder** [comment]
Dag Tim,

Het is de uiteindelijk de bedoeling dat we via de OAuth provider die Steven momenteel aan het implementeren is de gebruikersnaam e.d. ophalen. 


Groetjes
Bram
