### ISSUE TITLE
Lege dropdown op de gebruikers aanmaken pagina. 

### ISSUE THREAD

**Issue by Tjoosten** [ScoutsGidsenVL/groepsadmin-client#19]
Hi, 

De dropdown ''postadres is leeg. Nu is is mijn vraag kunnen we deze niet vullen met alle post adressen van België? 

<img width="457" alt="schermafbeelding 2016-04-14 om 17 01 51" src="https://cloud.githubusercontent.com/assets/5157609/14532858/cdf7679a-0262-11e6-9d3f-ee648ed40466.png">

**Comment by BramScheerder** [comment]
Dag Tim,

Vermoedelijk bedoel je alle postcodes van België.
Het postadres is het adres waarop het lid zijn persoonlijke briefwisseling ontvangt.
Er werd zonet een commit gedaan die het postadres verbergt als er minder dan 2 adressen zijn opgegeven.
